#!/bin/bash
# Usage: script/repl [ARGS...]
# Run a repl session capable of loading all of the components. Any passed arguments, e.g. module names or flags, will be passed to ghci.

set -e

cd "$(dirname "$0")/.."

cabal build all --only-dependencies

cabal exec env -- -u GHC_ENVIRONMENT ghci -ghci-script=.ghci.starlight $(script/ghci-flags) -no-ignore-dot-ghci $@
