#!/bin/bash
# Usage: script/repl [ARGS...]
# Run a repl session capable of loading all of the components. Any passed arguments, e.g. module names or flags, will be passed to ghci.

set -e

cd $(dirname "$0")/..

repl_builddir=dist-repl

if [[ ! -d $repl_builddir ]]; then
  cabal build --builddir="$repl_builddir" all --only-dependencies
fi

cabal exec --builddir="$repl_builddir" env -- -u GHC_ENVIRONMENT ghci -ghci-script=.ghci.starlight $(script/ghci-flags --builddir "$repl_builddir") -no-ignore-dot-ghci $@
